spring:
  application:
    name: simple-commerce

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/commerce
    username: sa
    password: 123

  jpa:
    database: h2
    open-in-view: false
    hibernate:
      ddl-auto: update # or update, create-drop, validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost
      port: 6379
  redisson:
    config:
      singleServerConfig:
        address:"redis://127.0.0.1:6379"
  kafka:
    bootstrap-servers: localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "project.simple_commerce.order.dto"