spring:
  application:
    name: simple-commerce

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/commerce
    username: sa
    password: 123

  jpa:
    database: h2
    open-in-view: false
    hibernate:
      ddl-auto: none # or update, create-drop, validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost
      port: 6379
  redisson:
    config:
      singleServerConfig:
        address:"redis://127.0.0.1:6379"